# Generated by Django 3.0.3 on 2020-08-06 04:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('species', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('breed', models.CharField(blank=True, max_length=64)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('source_website', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(max_length=64)),
                ('weight', models.FloatField(null=True)),
                ('liked_adopters', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Immune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('neuter', models.BooleanField(default=False)),
                ('heartgard', models.BooleanField(default=False)),
                ('nexgard', models.BooleanField(default=False)),
                ('rabies', models.DateField(null=True)),
                ('da2pp', models.DateField(null=True)),
                ('intra2', models.DateField(null=True)),
                ('extrainfo', models.TextField(null=True)),
                ('record_date', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petAdoption.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petAdoption.Pet')),
            ],
        ),
    ]
