# Generated by Django 3.0.3 on 2020-07-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petAdoption', '0002_adopter_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='favorites',
            field=models.ManyToManyField(to='petAdoption.Pet'),
        ),
        migrations.AddField(
            model_name='seller',
            name='pets_on_sale',
            field=models.ManyToManyField(to='petAdoption.Pet'),
        ),
    ]
