# Generated by Django 3.0.3 on 2020-07-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petAdoption', '0003_auto_20200710_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='favorites',
            field=models.ManyToManyField(null=True, to='petAdoption.Pet'),
        ),
    ]
