# Generated by Django 3.0.3 on 2020-07-10 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petAdoption', '0005_auto_20200710_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pet',
            name='post_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
