# Generated by Django 3.0.3 on 2020-07-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petAdoption', '0007_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(),
        ),
    ]
