# Generated by Django 3.0.3 on 2020-07-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petAdoption', '0008_auto_20200710_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
