# Generated by Django 3.0.3 on 2020-07-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petAdoption', '0009_auto_20200710_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
