# Generated by Django 3.0.3 on 2020-07-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petAdoption', '0010_auto_20200710_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='desciption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='postal_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='source_website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(max_length=64),
        ),
    ]
